/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JunitTesting;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class UserReg {
    public boolean someLibraryMethod() {
        return true;
    }

}
