/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JunitTesting;

import org.junit.*;
import org.junit.Assert;
import org.junit.rules.ExpectedException;
import org.junit.Assert;
public class UserRegTest {
	

	@Test
	public void givenFname_WhenProper_ShouldReturnTrue()
    {
		UserReg userValidator = new UserReg();
		boolean result=false;
		try {
			result = userValidator.validatefirstname("Ashutosh");
		} catch (UserRegistrationException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	Assert.assertTrue(result);
    }
	@Test
    public void givenFname_WhenProper_ShouldReturnFalse()
    {
		UserReg userValidator = new UserReg();
		boolean result=false;
		try {
			result = userValidator.validatefirstname("ashutosh");
		} catch (UserRegistrationException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		Assert.assertFalse(result);
    }
	@Test
    public void givenLname_WhenProper_ShouldReturnTrue()
    {
		UserReg userValidator = new UserReg();
		boolean result=false;
		try {
			result = userValidator.validatelastname("Aggarwal");
		} catch (UserRegistrationException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	Assert.assertTrue(result);
    }
	@Test
    public void givenLname_WhenProper_ShouldReturnFalse()
    {
		UserReg userValidator = new UserReg();
		boolean result=false;
		try {
			result = userValidator.validatelastname("aggarwal");
		} catch (UserRegistrationException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	Assert.assertFalse(result);
    }
	@Test
    public void givenEmail_WhenProper_ShouldReturnTrue()
    {
		UserReg userValidator = new UserReg();
		boolean result=false;
		try {
			result = userValidator.validateemail("abc@gmail.com");
		} catch (UserRegistrationException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	Assert.assertTrue(result);
    }
	@Test
    public void givenEmail_WhenProper_ShouldReturnFalse()
    {
		UserReg userValidator = new UserReg();
		boolean result=false;
		try {
			result = userValidator.validateemail("xyz@@gmail.com");
		} catch (UserRegistrationException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	Assert.assertFalse(result);
    }
	@Test
    public void givenPhNo_WhenProper_ShouldReturnTrue()
    {
		UserReg userValidator = new UserReg();
		boolean result=false;
		try {
			result = userValidator.validatephno("91 9888823512");
		} catch (UserRegistrationException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	Assert.assertTrue(result);
    }
	@Test
    public void givenPhNo_WhenProper_ShouldReturnFalse()
    {
		UserReg userValidator = new UserReg();
		boolean result=false;
		try {
			result = userValidator.validatephno("919888823512");
		} catch (UserRegistrationException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	Assert.assertFalse(result);
    }
	@Test
    public void givenPass_WhenProper_ShouldReturnTrue()
    {
		UserReg userValidator = new UserReg();
		boolean result=false;
		try {
			result = userValidator.validatepass("Tes@121313");
		} catch (UserRegistrationException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	Assert.assertTrue(result);
    }
	@Test
    public void givenPass_WhenProper_ShouldReturnFalse()
    {
		UserReg userValidator = new UserReg();
		boolean result=false;
		try {
			result = userValidator.validatepass("test@lfhwkf");
		} catch (UserRegistrationException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	Assert.assertFalse(result);
    }
	 
}