/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JunitTesting;

import org.junit.*;
import org.junit.Assert;
public class UserRegTest {
	
	@Test
	public void givenMessage_WhenSad_ShouldReturnSad()
	{
		UserReg moodAnalyser = new UserReg();
		String mood = moodAnalyser.analysemood("This is Sad message");
		Assert.assertEquals("SAD", mood);
	}
	//@Test
	public void givenMessage_WhenNotSad_ShouldReturnHappy()
	{
		UserReg moodAnalyser = new UserReg();
		String mood = moodAnalyser.analysemood("This is Happy message");
		Assert.assertEquals("HAPPY", mood);
	}
	//@Test
	public void givenFname_WhenProper_ShouldReturnTrue()
    {
		UserReg userValidator = new UserReg();
		boolean result = userValidator.validatefirstname("Ashutosh");
    	Assert.assertTrue(result);
    }
	//@Test
    public void givenFname_WhenProper_ShouldReturnFalse()
    {
		UserReg userValidator = new UserReg();
		boolean result = userValidator.validatefirstname("ashutosh");
		Assert.assertFalse(result);
    }
	//@Test
    public void givenLname_WhenProper_ShouldReturnTrue()
    {
		UserReg userValidator = new UserReg();
		boolean result = userValidator.validatelastname("Aggarwal");
    	Assert.assertTrue(result);
    }
	//@Test
    public void givenLname_WhenProper_ShouldReturnFalse()
    {
		UserReg userValidator = new UserReg();
		boolean result = userValidator.validatelastname("aggarwal");
    	Assert.assertFalse(result);
    }
	//@Test
    public void givenEmail_WhenProper_ShouldReturnTrue()
    {
		UserReg userValidator = new UserReg();
		boolean result = userValidator.validateemail("abc@gmail.com");
    	Assert.assertTrue(result);
    }
	//@Test
    public void givenEmail_WhenProper_ShouldReturnFalse()
    {
		UserReg userValidator = new UserReg();
		boolean result = userValidator.validateemail("xyz@@gmail.com");
    	Assert.assertFalse(result);
    }
	//@Test
    public void givenPhNo_WhenProper_ShouldReturnTrue()
    {
		UserReg userValidator = new UserReg();
		boolean result = userValidator.validatephno("91 9888823512");
    	Assert.assertTrue(result);
    }
	//@Test
    public void givenPhNo_WhenProper_ShouldReturnFalse()
    {
		UserReg userValidator = new UserReg();
		boolean result = userValidator.validatephno("919888823512");
    	Assert.assertFalse(result);
    }
	//@Test
    public void givenPass_WhenProper_ShouldReturnTrue()
    {
		UserReg userValidator = new UserReg();
		boolean result = userValidator.validatepass("Tes@121313");
    	Assert.assertTrue(result);
    }
	//@Test
    public void givenPass_WhenProper_ShouldReturnFalse()
    {
		UserReg userValidator = new UserReg();
		boolean result = userValidator.validatepass("test@lfhwkf");
    	Assert.assertFalse(result);
    }
	 
}
